### ISSUE TITLE
Safari Books Online version has obsolete github link

### ISSUE THREAD

**Issue by invegat** [l3x/learn-fp-go#2]
https://github.com/l3x/fp-go.git should be https://github.com/l3x/learn-fp-go

**Comment by superbmilkyway** [comment]
Not even Safari book, I purchased the book in Packt, all links in the images are not correct.
Please update books in Packt please.

**Comment by l3x** [comment]
Hey guys,  So sorry I'm just now noticing your message.

Did you know that the publisher has a revised version of the book available? It should be free.
(The original version was mostly a draft version that was hastily published, but has since been corrected.)

I'd highly recommend getting the revised version. The links there should be correct.

In the meantime, you might enjoy this presentation I gave for the Atlanta Functional Programming Meetup Group: https://www.youtube.com/watch?v=HRrP_P0PwFU

p.s. This is definitely the right place to create issues with the code/book, but feel free to link to me at https://www.linkedin.com/in/lexsheehan/ I'm likely respond more quickly there.

Thanks!
Lex
